# Generated by Django 2.2.2 on 2019-06-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, upload_to='job_images/')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'denied')], default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Job')),
            ],
            options={
                'unique_together': {('job', 'employee')},
            },
        ),
    ]
