# Generated by Django 2.2.2 on 2019-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190613_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_applicants',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
