# Generated by Django 2.2.2 on 2019-06-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190613_1820'),
        ('employees', '0002_auto_20190612_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hour_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Position')),
            ],
        ),
    ]
