# Generated by Django 2.2.2 on 2019-06-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190613_1820'),
        ('employees', '0003_auto_20190613_1911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeposition',
            unique_together={('employee', 'position')},
        ),
    ]
